services:
  nginx_production:
    container_name: nginx_production_container
    image: nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./build/public:/etc/nginx/html
      - ./.nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.cert/localhost-cert.pem:/etc/nginx/localhost-cert.pem
      - ./.cert/localhost-key.pem:/etc/nginx/localhost-key.pem

  postgres:
    container_name: postgres_container
    image: postgres:14-alpine
    ports:
      - 5433:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=new_db

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.local
    volumes:
      - .:/app
      - /app/node_modules
      - ./.cert:/root/.local/share/mkcert/
    ports:
      - 44310:44310
    environment:
      - NODE_ENV=development
